### ISSUE TITLE
Emphasis Area Componenet

### ISSUE THREAD

**Issue by leoneln** [leonelnieto/SHSP#13]
Reduce size to fit 11 tiles nicely snug in safety areas component. Each tile links to a component for each are. Add/edit the following tiles;
Emphasis Areas are:

Aggressive Driving
Distracted Driving
Impaired Driving
Motorcycle Safety
Pedestrian Safety
Roadway Departure Crashes
Intersection Safety
Speed Management
Teen Driving Safety
Use of Safety Restraints
Senior Mobility and Safety

**Comment by LiquPy** [comment]
Created a pull request (#17)
