### ISSUE TITLE
Emphasis Area Components 

### ISSUE THREAD

**Issue by leoneln** [leonelnieto/SHSP#14]
Add a component for each of the following emphasis areas;
Emphasis Areas are:

Aggressive Driving
Distracted Driving
Impaired Driving
Motorcycle Safety
Pedestrian Safety
Roadway Departure Crashes
Intersection Safety
Speed Management
Teen Driving Safety
Use of Safety Restraints
Senior Mobility and Safety

Use dummy data to populate charts.

**Comment by LiquPy** [comment]
Created a pull request (#17)
