### ISSUE TITLE
Continuing Safety Areas Component

### ISSUE THREAD

**Issue by leoneln** [leonelnieto/SHSP#15]
Create a continuing safety areas component and modify to fit the following tiles;
Bicycle Safety
Commercial Motor Vehicle Safety
Highway Railroad Crossing Safety
Rural Road Safety
Transit System Safety
Work Zone Safety
Connected and Autonomous Vehicles
Emergency Services
Traffic Incident Management
Traffic Data
Judicial System

**Comment by LiquPy** [comment]
Created a pull request ( #17)
